### ISSUE TITLE
Cannot create PostGIS table with geometries

### ISSUE THREAD

**Issue by mweisman** [boundlessgeo/suite-qgis-plugin#124]
Creating a table with a geometry column fails with `function addgeometrycolumn(unknown, unknown, unknown, integer, unknown, integer) does not exist LINE 1: SELECT AddGeometryColumn('public', 'test2', 'geom', -1, 'POI... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts.`

Tables without geometry columns can be created.

**Comment by Vitruvius21** [comment]
I have the same problem

**Comment by ashritha-hub** [comment]
Without postgis extension in postgresSQL, if you try to add any spatial layers to postgresSQL , you get above error.

In pgadmin right click on extensions and check whether postgis extension is saved or not.
if in extensions postgis option is absent ,you can follow these steps to 
 install postgis in postgres
 https://www.youtube.com/watch?v=afK8GWpb8RU
