### ISSUE TITLE
Cannot download OpenGeo Explorer 0.7.1 plugin for QGIS

### ISSUE THREAD

**Issue by kalafars** [boundlessgeo/suite-qgis-plugin#180]
Hi everybody,

I keep getting error messages (IE - "Download was interrupter", Chrome - "Failed-network error) when I try to download plugin for QGiS from http://qgis.boundlessgeo.com/opengeo/

The only version I can download is ver. 0.5 but I would like to use last release.

I've tried also to update ver. 0.5 in QGIS but with no success: "Plugin installation failed, operation cancelled"

Regards,
Michał

**Comment by dakcarto** [comment]
@volaya can you verify this? I have no problem downloading any of the versions here.

**Comment by volaya** [comment]
The server seems to  be working fine, from the Plugin Manager and from the
web itself

On Thu, Jun 11, 2015 at 5:43 PM, Larry Shaffer <notifications@github.com>
wrote:

> @volaya <https://github.com/volaya> can you verify this? I have no
> problem downloading any of the versions here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/boundlessgeo/suite-qgis-plugin/issues/180#issuecomment-111177894>
> .
>



-- 
Victor Olaya
Software Engineer | Boundless <http://boundlessgeo.com/>
volaya@boundlessgeo.com
@boundlessgeo <http://twitter.com/boundlessgeo/>

**Comment by dakcarto** [comment]
@kalafars Can not confirm here in US or from Europe. Might need to try again later, or restart any browsers or your computer.

**Comment by kalafars** [comment]
Hello @volaya, @dakcarto,

Thanks for checking this, I downloaded plugin at home without any issues. I think my problem was caused by company firewall.

**Comment by dakcarto** [comment]
Thanks for following up.
